### ISSUE TITLE
Document list of error codes

### ISSUE THREAD

**Issue by grant** [GoogleCloudPlatform/functions-framework#15]
The types of errors in the Function Frameworks should be described and standardized across languages.
This should include 400 and 500 errors.
400s: 400 Bad requests, 404s, 405s method not allowed
500s: Internal errors seen by the Functions Framework

**Comment by grant** [comment]
@grayside What do you think about documenting this expected behavior of HTTP status codes in the Functions Framework contract for HTTP-triggered functions? Anything I could be missing?

**Comment by grayside** [comment]
Hello Grant, I recommend documenting HTTP error codes the framework would use itself and not others, your list seems right to me.

I've also seen error codes such as `5` in the CloudEvents mode with the nodejs framework, could we get those documented as well?

**Comment by grant** [comment]
Thanks for the reply Adam. I don't know of error codes such as `5`.
Here is the spec:
https://github.com/cloudevents/spec/blob/master/primer.md#protocol-error-handling

I've looked at the Node.js Framework source and found some interesting cases but nothing like a non-HTTP error codes or common Node error codes.

**Comment by grayside** [comment]
I've double-checked, and found `5 NOT_FOUND: <...>` which looks like its coming from a pre-alpha library. This is probably a gRPC error code which neither my code nor the functions framework wrapped for better context. This probably doesn't affect this issue, but possibly is a consideration for error handling.

**Comment by grant** [comment]
A few of us have talked about this topic in the .NET FF meeting. Greg Block chimed in.

I've created a proposal for documenting the acceptable error codes in the PR above.
