### ISSUE TITLE
The README doc on the flag "--target" is confusing: does not exist in gcloud functions deploy.

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/functions-framework#17]
The readme lists some flags. Not sure for which tool?

For example, the flag "--target" does not exist in gcloud functions deploy... What is the mapping? Should be stay consistent?

**Comment by grant** [comment]
gcloud, Google Cloud Functions, and the Functions Frameworks are separate.

For `--target`, that feature isn't added to Cloud Functions, although you could create your own container and deploy to Cloud Run.

These technologies will evolve separately and will have additional features. If you have a recommendation for a specific change, let me know!

**Comment by grant** [comment]
Hope the above answers the question. Please re-open if there are further questions about this topic.
