### ISSUE TITLE
Clarify FUNCTION_TARGET and FUNCTION_NAME

### ISSUE THREAD

**Issue by jskeet** [GoogleCloudPlatform/functions-framework#19]
My understanding is now that FUNCTION_NAME is effectively used to register a function, whereas FUNCTION_TARGET is the (platform specific) target of the function, e.g. a Java class name or a .NET type name.

It would be useful to clarify this in the README - it jumps straight from FUNCTION_TARGET to FUNCTION_NAME without explaining that difference. It certainly confused me - it's possible I'm the only one, but I suspect not.

**Comment by grant** [comment]
FUNCTION_NAME is only used in the product Google Cloud Functions (API/CLI/UI). It's not part of the FF contract. It's the FaaS alias for a function, like a username.

It's confused me. Not sure how to better spell it out.

**Comment by jskeet** [comment]
Okay - I may put together a PR with the start of a suggestion. It's the kind of thing that's worth iterating on :)

**Comment by grant** [comment]
> Okay - I may put together a PR with the start of a suggestion. It's the kind of thing that's worth iterating on :)

Looking forward to the PR.

**Comment by grant** [comment]
I created a simple PR to fix this.
