### ISSUE TITLE
functions-framework-deno

### ISSUE THREAD

**Issue by jthegedus** [GoogleCloudPlatform/functions-framework#24]
It would be great to know if Google is intending on working on a `functions-framework` for [Deno](https://github.com/denoland/deno).

I saw this example for [Deno on Cloud Run](https://medium.com/google-cloud/deno-on-cloud-run-89ae64d1664d) on the Google-Cloud Medium publication and was wondering if there is an intent to build this?

I didn't know where else to ask.

**Comment by grant** [comment]
There is no plans now. I've moved this to the overall FF repo and added a tag for a new runtime FR.

It's fundamentally different, so it would require a new repo.

**Comment by grant** [comment]
I created a sample repo here:

https://github.com/GoogleCloudPlatform/functions-framework/issues/49

But there are no plans for more support here for this runtime at the moment. I'll close this open issue, but feel free to keep commenting. Feel free to keep using my blogpost linked above as a reference for deploying Deno on serverless :)
