### ISSUE TITLE
functions-framework-swift 

### ISSUE THREAD

**Issue by stephenhandley** [GoogleCloudPlatform/functions-framework#27]
Is there any plan to have a Swift runtime implementation at some point in the future?

**Comment by grant** [comment]
No plans right now. Do you have interest? What is your use-case for Swift functions?

**Comment by stephenhandley** [comment]
@grant Mainly just wondering as have been seeing more server side frameworks for Swift popping up (Vapor, Kitura, Perfect) and some of the experimental language features look interesting https://tryolabs.com/blog/2020/04/02/swift-googles-bet-on-differentiable-programming/

**Comment by grant** [comment]
Oh cool. That sounds really cool.
I never knew about https://github.com/tensorflow/swift.

Sounds like it could be a good serverless framework.
Would we use something like https://github.com/Alamofire/Alamofire?

**Comment by stephenhandley** [comment]
Yeah! Just found out about the tensorflow differentiable programming stuff myself and looks really interesting. Honestly have been in js land for too long and swift is looking more and more compelling. Alamofire looks cool, hadn't heard of that. Here's a couple of the others I've seen, but don't have any deep experience using them yet.

**Vapor**
https://vapor.codes/
https://github.com/vapor/vapor

**Kitura**
https://www.kitura.io/
https://github.com/ibm-swift/kitura

**Perfect**
https://perfect.org/
https://github.com/PerfectlySoft/Perfect

**Comment by grant** [comment]
@stephenhandley I published a blogpost showing how to deploy Swift on Cloud Run:

Blogpost:
https://medium.com/google-cloud/swift-on-cloud-run-b6397a428d

Tweet:
https://twitter.com/GCPcloud/status/1279867647132225537

I don't know how much benefit a FF for swift would be, as the application code is really simple.

**Comment by stephenhandley** [comment]
Awesome, thanks @grant I'll check that out!

**Comment by grant** [comment]
Thanks for the issue. Since we haven't gotten much demand for this language based on this issue's activity and due to issue prioritization, I'm going to close the issue. If we want to re-open the issue in the future, or keep commenting, that is available! The deploy to Cloud Run option is a good workaround.
