### ISSUE TITLE
functions-framework-dart

### ISSUE THREAD

**Issue by SogoGolf** [GoogleCloudPlatform/functions-framework#40]
Are there any plans to add Dart to the list of supported languages?

**Comment by grant** [comment]
Nothing public yet but thanks for opening this issue!
If you have any requests / use-cases, please comment.

**Comment by SogoGolf** [comment]
We're migrating (almost done) an existing iOS/Android native app, to Flutter. The whole dev experience has been AMAZING (we've used 'em all, Xamarin, React Native, ...). Part of that great experience has also been working with Dart. So we'd love to be able to use Dart server side now too via the functions framework. We've got a serverless/microservice setup so for us at least, being able to write/deploy Dart based functions would be the cherry on top.

**Comment by Zfinix** [comment]
> We're migrating (almost done) an existing iOS/Android native app, to Flutter. The whole dev experience has been AMAZING (we've used 'em all, Xamarin, React Native, ...). Part of that great experience has also been working with Dart. What a great language. So we'd love to be able to use Dart server side now too via the functions framework. We've got a serverless/microservice setup so for us at least, being able to write/deploy Dart based functions would be the cherry on top.

I would definitely love to build web-based applications with dart hosted on GCP

**Comment by graphicbeacon** [comment]
Amazon Lambda team added support for the Dart runtime a couple of months ago so it makes sense for the Google Cloud team to have this too.

**Comment by subfuzion** [comment]
So the good news is that we are in fact in the early incubation stages of working on a Functions Framework for Dart. We are intent on providing a good developer experience along with solid performance.

One area of focus has been slimming down image size for functions containers (if you're interested in checking that effort out, see this [repo](https://github.com/subfuzion/dart-docker-slim) -- this is not officially supported yet, but feedback is welcome).

For developer experience, we'd love to hear more about any use cases you have. I for one am feeling enthusiastic about the Flutter frontend / Dart serverless backend combination. Looking forward to comments!

**Comment by subfuzion** [comment]
Hey folks, I'm happy to share the progress we've been making with an early cut at the Functions Framework for Dart.

It's early stage, doesn't yet support cloudevents (so doesn't pass Functions Framework conformance tests), so it's not yet ready for real-world use.

But since we'd like to start getting community feedback on expectations and use cases ... (drumroll 🥁) ... here it is:

https://github.com/GoogleCloudPlatform/functions-framework-dart

I am pleased to inform all you Dart enthusiasts out there that early informal benchmarks for Cloud Run are on par with Go and Node.js. If you're already a Flutter fan and want to use Dart functions on the backend, we think you're going to be quite pleased. Please share your comments, requests, and issues in that repo, not this one.

Happy Thanksgiving from the Dart and Cloud Functions / Serverless teams at Google!

**Comment by SogoGolf** [comment]
Woohoooo!

**Comment by graphicbeacon** [comment]
Great work team! Glad to see this coming to fruition. @subfuzion What do I need to read up on if I wish to contribute?

**Comment by subfuzion** [comment]
@graphicbeacon If you want to contribute, that's awesome. I'll start copying issues over from the private internal repo we had. I'd start with reading the Functions Framework Conformance [requirements](https://github.com/GoogleCloudPlatform/functions-framework-conformance).

I've got a branch for `cloudevent` support in work, but testing, helping to identify issues, and helping to flesh out more `http` function examples would be great.

Would love to get feedback / feature requests in terms of real world enterprise use cases.

**Comment by subfuzion** [comment]
Note: As with [C++](https://github.com/GoogleCloudPlatform/functions-framework-cpp) and [R](https://github.com/averikitsch/functions-framework-r), this is not yet officially supported by Google Cloud, and it is not yet production ready.

But we're seeing a lot of interest in the community, so your 'likes' on this issue and for the actual [Dart repo](https://github.com/GoogleCloudPlatform/functions-framework-dart), and your feedback, feature requests, and contributions there demonstrating community enthusiasm/support, will help to accelerate things and make the case for an officially supported Google runtime on [Cloud Functions](https://cloud.google.com/functions/) and [Cloud Functions for Firebase](https://firebase.google.com/docs/functions/).

I personally feel that 2021 is going to be a great year for Dart and Flutter growth in the enterprise. Stay tuned and stay involved!

**Comment by grant** [comment]
As mentioned in https://github.com/GoogleCloudPlatform/functions-framework/issues/40#issuecomment-731506743, we have a repo for Dart!

https://github.com/GoogleCloudPlatform/functions-framework-dart

Will close this Functions Framework repo issue and let discussion continue in that specific language repo. :)
