### ISSUE TITLE
Support and respect .env file for loading environment variables in local development

### ISSUE THREAD

**Issue by greg76** [GoogleCloudPlatform/functions-framework#43]
During local development it would be a great help if running functions_framework would load environment variables from the dotenv file, just as flask does. This would streamline the development process.

**Comment by grant** [comment]
Hi @greg76,
I'm not sure if everybody wants their functions to load a file before development. With local dev, you can just call a 1-2 line function in most languages like:

```py
from dotenv import load_dotenv
load_dotenv()
```

Or load an env file in your shell:

https://stackoverflow.com/questions/19331497/set-environment-variables-from-file-of-key-value-pairs

Do you have a more concrete proposal? Or existing pain? I can't tell.

**Comment by grant** [comment]
Given it's relatively simple to load env files in your function, and there's no reply here, I'm closing the issue. Thanks!
