### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by algoflows** [GoogleCloudPlatform/functions-framework#60]
Kotlin picking up steam, it's a Google backed language, yet I see no support across any of the function stacks including Firebase Functions. It's starting to grate, so I've asked Digital Ocean to see if they'll support Kotlin before google does.

**Comment by josephlewis42** [comment]
Hi @algoflows, [Cloud Functions should support Kotlin today via the Java Functions Framework](https://cloud.google.com/functions/docs/concepts/jvm-langs). As a Kotlin developer, what else would be useful for you when developing functions to make the experience better for you?

Thanks!

**Comment by josephlewis42** [comment]
I'm going to close this for now, since I think Kotlin for most server use-cases would be covered under the JVM buildpack. If there's anything we can do to further improve the developer experience feel free to re-open because we'd love to hear more!
